# Generated by Django 5.2.3 on 2025-06-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagehistory',
            options={'ordering': ['-edited_at'], 'verbose_name': 'Message Edit History', 'verbose_name_plural': 'Message Edit Histories'},
        ),
    ]
